### ISSUE TITLE
How to install an application?

### ISSUE THREAD

**Issue by Tezigudo** [StandUpCode/BankAPIConnect#1]
I run docker compose and get this
<img width="751" alt="image" src="https://user-images.githubusercontent.com/80502090/197429426-4f3db418-a78d-470a-a0e2-dcb0ef7121f3.png">

I have created .env file and running docker So, I dont know how to do futhor more

**Comment by Tezigudo** [comment]
what configuration file that it mean

**Comment by pattanun-np** [comment]
It mean you need to have api key from kbank and scb first 
create .env file with .env.example
